### ISSUE TITLE
Ignore signs with colored text

### ISSUE THREAD

**Issue by Madis0** [gbl/ClickThrough#1]
How about, instead of specific regex matching, you ignore all signs that have non-survival colors, aka the base colors that are available with the paragraph sign.

**Comment by gbl** [comment]
That won't help people on servers with Chest shops, those signs are generally default black.

But this is an idea for an additional option, or several additional options: "ignore signs that have formatting", and "ignore signs that have formatting that can't be obtained in vanilla", which would include bold, italic, and all that as well.
