### ISSUE TITLE
Hide config icon

### ISSUE THREAD

**Issue by Ayutac** [gbl/ClickThrough#13]
Hi there, I like this mod, but I dislike that the config item is shown on start, item screen and pause. Please add option to hide it. If I want to config, I go to the config files on my pc

**Comment by gbl** [comment]
Install ModMenu, the config icon is only shown if modmenu isn't present.

**Comment by Ayutac** [comment]
will you accept a PR with my solution, configurably not shown, having it shown by default if no mod menu is present?

**Comment by gbl** [comment]
No. The config system is used in all of my mods, more than 10. It would be a huge hassle to do that in all mods, most of which have versions going back to 1.14, and break the expectations of all those mod users.

**Comment by Ayutac** [comment]
First of, adding a config option that defaults to the old value doesn't break anything.

Secondly, the icon is intrusive, this is just a boolean flag to change, and the answer to a boolean flag change should never be "Just install mod X to change the flag."

**Comment by Ayutac** [comment]
I apologize for my rudeness in the previous post. I don't know why your No has tilted me that much. It is your mod to do with as you wish. Have a nice week :-)
