### ISSUE TITLE
1.19 Please!

### ISSUE THREAD

**Issue by taciturnaxolotl** [gbl/ClickThrough#14]
I would be willing to help update to 1.19 but will need some direction of how to do this.

**Comment by gbl** [comment]
I'm planning to do the updates (of all my mods, not just ClickThrough) this weekend.

In the meantime, you could try if the 1.19-pre2 version at https://modrinth.com/mod/clickthrough/version/1.19-pre2-fabric0.53.3-0.4 works for you, as there have been very little changes between pre2 and the final 1.19.

**Comment by taciturnaxolotl** [comment]
Thanks!
