### ISSUE TITLE
Feature request: Toggle option

### ISSUE THREAD

**Issue by MageAtoru** [gbl/ClickThrough#16]
Hey

I would love to see a toggle option / keybind as even doh we have sneak that lets you interact with item frames and signs there are scenarios that are incompatible like "edit signs with a right click"

**Comment by ChristopherHaws** [comment]
I am also having issues with our server's "edit signs with a right click" plugin. I think a good way to implement this would be to have a way to specify an item (or a list of items) which does not pass through the sign. Our server uses a plugin which lets you edit signs if your right click on the sign with only an axe. If I could disable this mod only when I am holding an axe, that would make it work with our server's plugin. :)

**Comment by MageAtoru** [comment]
well we have to right click with a sign in our hand on a sign to edit it... still hoping a solution will be implemented

**Comment by Zarepheth** [comment]
I've encountered a structure in the modpack I'm playing where I believe I need to manipulate some item frames. However, right-clicking the item frame does nothing, I see a momentary flash as the block behind the frame has its info show up in Jade, but the item fails to rotate on the frame.

**Comment by Zarepheth** [comment]
I don't know what happened, but after restarting Minecraft, I was able to sneak-interact with the item frame. I had tried earlier, but that didn't make a difference. After starting a new Minecraft session, then it worked.

**Comment by RhythmicSys** [comment]
Came here to also make this feature request, my server uses sneak to turn item frames invisible, resulting in the issue where items cannot be rotated with this mod enabled since you have to sneak to stop from clicking through- which then causes the item frame on the server to go invisible and lock. Having a toggle or a keybind that can be altered would be very helpful

**Comment by gbl** [comment]
Done in the 1.20 version.
