### ISSUE TITLE
Crashing when opening config

### ISSUE THREAD

**Issue by t0mtee** [gbl/ClickThrough#21]
[Log](https://crashy.net/08f1a3c9-42ef-493f-8480-b3df7ccc0465)

**Comment by aaron01-dev** [comment]
you must be on version 1.19.4 as the mod author stated on their mod page, 1.19.4 changed a lot of things with gui but the mod itself is still working but you can't configure it in game anymore.

**Comment by t0mtee** [comment]
Just realised that this log is completely wrong... like completely. It must be someone else's and the link is wrong. I'm actually using 1.19.4 and can provide a correct log if needed.

**Comment by gbl** [comment]
As aaron said, the config didn't work with 1.19.4, but it works again now with the 1.20/1.20.1 version.
