### ISSUE TITLE
Update the mod, someone, please

### ISSUE THREAD

**Issue by QueenUlyana** [gbl/ClickThrough#23]
### **Please update to 1.19.4**

**Comment by gbl** [comment]
It is updated (to 1.20/1.20.1) now.

**Comment by QueenUlyana** [comment]
> It is updated (to 1.20/1.20.1) now.

Can I get a link?

**Comment by QueenUlyana** [comment]
> It is updated (to 1.20/1.20.1) now.

Stop! There are versions for 1.20, and I need it for 1.19.4.

**Comment by QueenUlyana** [comment]
I see a version for 1.19.3, but not for 1.19.4.

**Comment by gbl** [comment]
sorry, I omitted 1.19.4 as it's old now

**Comment by gbl** [comment]
https://modrinth.com/mod/clickthrough/version/1.19.4-fabric0.76.0-0.4 resp.  https://legacy.curseforge.com/minecraft/mc-mods/clickthrough/files/4614632 should work, they're a quick backport from the 1.20 version. You'll also need cloth config (https://modrinth.com/mod/cloth-config/version/10.0.96+fabric). No guarantees though.

**Comment by QueenUlyana** [comment]
> https://modrinth.com/mod/clickthrough/version/1.19.4-fabric0.76.0-0.4 resp. https://legacy.curseforge.com/minecraft/mc-mods/clickthrough/files/4614632 should work, they're a quick backport from the 1.20 version. You'll also need cloth config (https://modrinth.com/mod/cloth-config/version/10.0.96+fabric). No guarantees though.

I checked, everything works. Thank you!
