### ISSUE TITLE
Cannot Edit Signs Placed On Chests

### ISSUE THREAD

**Issue by Avakining** [gbl/ClickThrough#29]
1.20 added the ability to edit placed signs, but this mod disabled that ability when signs are placed on chests.

**Comment by gbl** [comment]
The mod has a new key, F9 (can be rebound) to turn the mod off and on. If you're low on keys, bind the key to nothing, and use /clt on and /clt off. With clickthrough off, you can do whatever you want in the standard way - rewrite signs, dye them, or rotate item frames.
