### ISSUE TITLE
Config screen for ClickThrough has failed to load

### ISSUE THREAD

**Issue by RefaelNesss88** [gbl/ClickThrough#30]
![image](https://github.com/gbl/ClickThrough/assets/105297056/7f98ea91-1db0-4d55-ad12-257cf936b1f7)

**Comment by gbl** [comment]
Please send the whole log, especially the part with the list of mods and version you're using.

**Comment by RefaelNesss88** [comment]
Im using Fabric 1.20.1

* Mod List 81:
    3dskinlayers-fabric-1.5.3-mc1.20.jar
    advancementinfo-1.20-fabric0.83.0-1.3.1.jar
    animatica-0.6+1.20.jar
    antighost-1.19.3-fabric0.68.1-1.1.5.jar
    appleskin-fabric-mc1.20-2.5.0.jar
    armorchroma-1.2.6.jar
    BetterF3-7.0.0-Fabric-1.20-pre6.jar
    bettermounthud-1.2.2.jar
    blur-3.1.0.jar
    Boat-Item-View-Fabric-1.20.1-0.0.5.jar
    borderless-mining-1.1.8+1.20.1.jar
    capes-1.5.2+1.20-fabric.jar
    chatsounds-1.1.9.jar
    chat_heads-0.10.16-fabric-1.20.jar
    CITResewn-1.1.3+1.20.jar
    clickthrough-1.20-fabric0.83.0-0.4.jar
    cloth-config-11.0.99-fabric.jar
    continuity-3.0.0-beta.2+1.20.jar
    Controlify-1.3.1+1.20.jar
    Controlling-fabric-1.20.1-12.0.1.jar
    Craftify-1.20.1-1.11.0-fabric.jar
    Debugify-1.20.1+1.1.jar
    desktop.ini
    do-a-barrel-roll-3.0.1+1.20-fabric.jar
    dynamic-fps-2.4.0.jar
    e4mc-3.2.0+1.19.4-fabric.jar
    easiervillagertrading-1.20-fabric0.83.0-1.5.4.jar
    eating-animation-1.9.4+1.20.jar
    emoji-type-2.1.0+1.20.jar
    enhancedblockentities-0.9+1.20.jar
    entityculling-fabric-1.6.2-mc1.20.jar
    entity_model_features_fabric_1.20-0.2.11.jar
    entity_texture_features_fabric_1.20-4.4.4.jar
    fabric-api-0.84.0+1.20.1.jar
    fabric-language-kotlin-1.9.6+kotlin.1.8.22.jar
    fabricskyboxes-0.7.1+mc1.20.jar
    fabrishot-1.9.2.jar
    fadeless-1.0.1.jar
    farsight-fabric-1.20.1-3.7.jar
    Fastload+1.18.2-1.20-3.4.0.jar
    fastquit-3.0.0-beta.2+1.20+.jar
    ferritecore-6.0.0-fabric.jar
    fsb-interop-1.3.2+mc1.20-build.36.jar
    fullscreeNO-1.0.0.jar
    ImmediatelyFast-1.1.15+1.20.1.jar
    indium-1.0.18+mc1.20.jar
    InventoryProfilesNext-fabric-1.20-1.10.5.jar
    iris-mc1.20-1.6.4.jar
    Jade-1.20-fabric-11.1.4.jar
    lambdynamiclights-2.3.1+1.20.1.jar
    language-reload-1.5.8+1.20.1.jar
    lazydfu-0.1.3.jar
    libIPN-fabric-1.20-3.0.2.jar
    lithium-fabric-mc1.20.1-0.11.2.jar
    main-menu-credits-1.1.2.jar
    MapTooltip-fabric-1.20-3.0.0.jar
    memoryleakfix-fabric-1.17+-1.1.1.jar
    mixintrace-1.1.1+1.17.jar
    modelfix-1.14-fabric.jar
    modmenu-7.1.0.jar
    morechathistory-1.19.1-1.1.1.jar
    moreculling-1.20-0.18.1.jar
    nmuk-1.1.0+mc1.20-pre2.jar
    NoChatReports-FABRIC-1.20.1-v2.2.2.jar
    notenoughanimations-fabric-1.6.4-mc1.20.jar
    optigui-2.1.2.jar
    puzzle-1.5.1+1.20.jar
    reeses_sodium_options-1.5.1+mc1.20-build.74.jar
    Rrls-1.20.1-3.1.0-fabric.jar
    Searchables-fabric-1.20.1-1.0.1.jar
    shulkerboxtooltip-fabric-4.0.3+1.20.jar
    sodium-extra-0.4.20+mc1.20-build.103.jar
    sodium-fabric-mc1.20-0.4.10+build.27.jar
    soundphysics-fabric-1.20.1-1.1.1.jar
    tooltipfix-1.1.1-1.20.jar
    trade-cycling-fabric-1.20.1-1.0.5.jar
    visuality-0.7.0+1.20.jar
    Xaeros_Minimap_23.5.0_Fabric_1.20.jar
    yet-another-config-lib-fabric-3.0.2+1.20.jar
    yosbr-0.1.2.jar
    Zoomify-2.10.0.jar

* Log:
[latest.log](https://github.com/gbl/ClickThrough/files/11902998/latest.log)

**Comment by gbl** [comment]
There should be a button somewhere to show the log while the game is running. Sorry, can't tell for sure, because I've been using MultiMC for ages and don't even know what the standard launcher looks like anymore.

**Comment by RefaelNesss88** [comment]
i gtg sleep now lol, so tmrw ill do that. good night :)

**Comment by RefaelNesss88** [comment]
Good morning, ive updated my message, with the mods and log

**Comment by gbl** [comment]
Thank you! Could you please drop the jar file from https://github.com/gbl/GBfabrictools/releases/download/1.4/GBfabrictools-1.4+1.20.jar  into your mods folder and check if that fixes the problem?

**Comment by RefaelNesss88** [comment]
Yes, I can open the Config menu now. Thanks!
