### ISSUE TITLE
нет настройки в modmenu

### ISSUE THREAD

**Issue by ragoke** [gbl/ClickThrough#31]
при наведении на мод, modmenu показывает ошибку
![Screenshot 2023-06-30 004758](https://github.com/gbl/ClickThrough/assets/67712287/0db2a02b-cf9e-429a-9c5e-0e6c2c756980)

**Comment by gbl** [comment]
Sorry, I don't speak Ukrainian, but I can still see the error message.  It should go away if you drop the jar from https://github.com/gbl/GBfabrictools/releases/tag/1.4 into your mods folder. Will publish a fixed version of ClickThrough soon.
