### ISSUE TITLE
Wall sign can't be edited

### ISSUE THREAD

**Issue by MaoYan5985** [gbl/ClickThrough#32]
Wall sign can't be edited, no matter the sign is in front of chest or not.
I tried right click and shift + right click the wall sign, nothing happened.
Maybe add a toggle like dyeing the sign is better.

- MC : 1.20.1
- Fabric : 0.14.22
- clickthrough-1.20-fabric0.83.0-0.4.1

**Comment by gbl** [comment]
Use /ctl off to completely disable the mod, then edit the sign, then /ctl on to reenable it. (Or press F9 unless you've rebound that key).
