### ISSUE TITLE
Ignore signs without a container behind it

### ISSUE THREAD

**Issue by Toseflo** [gbl/ClickThrough#4]
We have many ServerSigns on our server and it's a bit problematic that I have to sneak every time I want to activate a ServerSign. But I think this could be fixxed if you would ignore signs without a container behind it. Most ServerSigns don't have a container behind them, so just retaining normal right click functionality when there isn't a container present would probably help.

**Comment by gbl** [comment]
Doing this unconditionally would break compatibility with all other mods that add containers, and stuff that isn't a container but has a right-click action, like noteblocks, jukeboxes, ... - so it would have to be a config option.

Isn't there any way to distinguish your ServerSigns from others, like a certain keyword in a certain row, that you can add to the exception list?

**Comment by Toseflo** [comment]
The problem is that ServerSigns can have custom text, so distinguishing them sadly shouldn't be possible. And yes a config option would be great ^^

**Comment by gbl** [comment]
Done in version 0.4 which I just published.
