### ISSUE TITLE
Feature request: ClickThrough String

### ISSUE THREAD

**Issue by RasmusKD** [gbl/ClickThrough#5]
ClickThrough String would be useful for villager halls where you have your villagers stand in a string so an observer can detect the villager is there to close the booth.

Making string-clickthrough would make it even easier to click the villager as you often target the string's hitbox.

**Comment by gbl** [comment]
Not closing this right now, but it probably won't get implemented as this isn't how ClickThrough works. 
When it detects a block click, and the block that gets clicked is a sign or an item frame, the clicked block gets replaced by the block that the original one is attached to. ClickThrough never messes with hitboxes, it doesn't have a "replace a block click with an entity click" feature, and I'd have to do something like "when raytracing, and the ray hits a string, ignore the string and keep raytracing, but only if the user just right-clicked". That's a bit out of the scope of this mod.
