### ISSUE TITLE
Causes MC to crash on launch

### ISSUE THREAD

**Issue by Hyperbean18** [gbl/ClickThrough#7]
My log:
[latest.log](https://github.com/gbl/ClickThrough/files/6329446/latest.log)

**Comment by gbl** [comment]
You have two versions of the mod installed at the same time, from the log:




/Users/SAATHVIK/Library/Application%20Support/minecraft/mods/clickthrough-1.16.5-fabric0.30.0-0.4.jar
/Users/SAATHVIK/Library/Application%20Support/minecraft/mods/clickthrough-1.16.4-fabric0.25.1-0.3.jar
